/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/stages/{stage}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Stage */
        post: operations["run_stage_api_projects__project_id__stages__stage__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job Events
         * @description §11.4: `event: progress` 形式の SSE。
         */
        get: operations["job_events_api_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/audio/original": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Original Audio
         * @description §11.6: 原曲配信。HTTP Range 対応(Starlette FileResponse がネイティブに対応)。
         *
         *     原曲は拡張子が可変(mp3/wav/flac/m4a)なため、DBに記録された `audio_format` を
         *     介して `service.audio_path_for_project()` で解決する(`storage.find_original_audio()`
         *     のようなファイルシステム側の拡張子探索には頼らない)。一方、分離後のステムは
         *     常に固定で `.wav`(#16の出力仕様)であり、DBに形式を持たせる意味が無いため、
         *     下の `get_stem_audio` は `storage` 経由で直接パスを組み立てる。同一ファイル内で
         *     解決方式が2通りあるのは、この拡張子が可変か固定かの違いに起因する意図的な差分。
         */
        get: operations["get_original_audio_api_projects__project_id__audio_original_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/audio/stems/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stem Audio
         * @description #16/#21: ステム配信。Range 対応(既存の /audio/original と同じパターン)。
         *
         *     ステムは常に `.wav` 固定(#16)なのでDB参照は不要。`get_original_audio` との
         *     パス解決方式の違いについては同関数のdocstringを参照。
         */
        get: operations["get_stem_audio_api_projects__project_id__audio_stems__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/stems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Stems
         * @description #21 TrackList: 分離済みステム名の一覧を返す(分離ステージ未実行時は空リスト)。
         *
         *     フロントはこれでステム名を知るまで `/audio/stems/{name}` の存在する `name` を
         *     知る手段が無い(#16のプリセットごとにステム名の集合が異なるため、固定リストを
         *     ハードコードできない)。空リストは404ではなく200で返す: 分離未実行は正常な
         *     初期状態であり、エラーではないため。
         */
        get: operations["list_stems_api_projects__project_id__stems_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/analysis/peaks/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Peaks
         * @description #21: 波形ピークデータ。初回計算し `analysis/peaks/{name}.json` にキャッシュする。
         *
         *     `async def` ではなく通常の `def` にする(#20-M1レビュー指摘の追加ラウンド)。
         *     初回計算時は `compute_peaks`(`sf.read` によるWAV全体の読み込み+numpy計算)を
         *     呼ぶため、`async def` のままだとイベントループを直接ブロックし、SSEでのジョブ
         *     進捗配信など他の同時リクエスト全体を止めてしまう(NFR-04の「重いDSPはWorker
         *     プロセスへ分離する」方針とも矛盾する)。FastAPIは同期`def`のエンドポイントを
         *     自動的にスレッドプールで実行するため、これだけでイベントループを塞がなくなる。
         */
        get: operations["get_peaks_api_projects__project_id__analysis_peaks__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/analysis/beatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Beatmap
         * @description #18: `beatmap.json` をそのまま返す。
         */
        get: operations["get_beatmap_api_projects__project_id__analysis_beatmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Beatmap
         * @description #20 BeatGridEditor: 手動補正を beatmap.json に反映する(FR-04)。
         */
        patch: operations["patch_beatmap_api_projects__project_id__analysis_beatmap_patch"];
        trace?: never;
    };
    "/api/projects/{project_id}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Score
         * @description Stage 3(採譜)未実行なら404を返す。
         *
         *     `async def` ではなく通常の `def` にする(`api/export.py`の`export_score`と
         *     同じ理由、#27-M2レビュー指摘): `ScoreService.read_score`はファイルI/Oを
         *     伴う同期処理であり、`async def`のままだとイベントループを直接ブロックし、
         *     SSEでのジョブ進捗配信など他の同時リクエストを止めてしまう。
         *
         *     `response_model`に`domain.score.ScoreIR`を直接指定しない: そのネストする
         *     `TempoMapEntry`/`TimeSignatureEntry`が`api/schemas.py`(beatmap用)の同名
         *     クラスとOpenAPIコンポーネント名で衝突し、生成TSの型名が
         *     `app__api__schemas__TempoMapEntry`等へ改名されてしまう(#23-M2レビュー
         *     指摘)。M2のフロントエンドはこのエンドポイントの型付けを必要としない
         *     (設計書§11.5の完了条件外)ため、素の`dict`で返し衝突を避ける。
         */
        get: operations["get_score_api_projects__project_id__score_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/score/ops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply Score Ops
         * @description #31: ノート編集オペレーションを配列で一括適用する(FR-09)。
         *
         *     `async def` ではなく通常の `def` にする(`get_score`/`export_score`と同じ
         *     理由): ファイルI/Oが中心の同期処理。
         *
         *     楽観的並行性制御(`worker/dsp_main.py`の各ステージ、`patch_beatmap`と同じ
         *     パターン): リクエスト開始時に読んだ生JSON(`raw_before`)を保持し、
         *     `apply_ops`はその場でパースした`ScoreIR`(まだ書き込んでいない)に対して
         *     行う。書き込み直前に再読込して`raw_before`と一致するか確認し、不一致なら
         *     409(`_read_score_raw_or_404`のdocstring参照)。
         *
         *     #32-M3レビュー指摘: `score/current.json`だけでなく`score/undo_state.json`も
         *     同じ比較対象に含める。このエンドポイントは`_record_edit_or_warn`経由で
         *     undo_state.jsonも更新するため、対象に含めないと「本リクエストが
         *     score/ops.jsonlへ追記→undo_state.jsonを更新するまでの間に、別リクエスト
         *     (`/score/undo`等)がundo_state.jsonを読んで書き換える」という競合を
         *     見逃し、どちらか一方の更新が消える(lost update)。ただし
         *     `_record_edit_or_warn`自身がこのチェックの後でundo_state.jsonを再度
         *     読み直すため、そこから実際に書き込むまでの狭い窓は依然として残る
         *     (`patch_beatmap`等で既に許容されているのと同種の、単一ユーザー向け
         *     デスクトップアプリとして許容するTOCTOUギャップ)。
         */
        post: operations["apply_score_ops_api_projects__project_id__score_ops_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/score/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Undo Score Ops
         * @description #32: 直近の編集を1つ元に戻す。Undoスタックが空なら`applied=false`で200を返す
         *
         *     (「元に戻す操作が無い」はエラーではないため)。
         */
        post: operations["undo_score_ops_api_projects__project_id__score_undo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/score/redo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redo Score Ops
         * @description #32: 直近にUndoした編集を1つやり直す。Redoスタックが空なら`applied=false`で
         *
         *     200を返す。
         */
        post: operations["redo_score_ops_api_projects__project_id__score_redo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/score/preview.musicxml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Score Preview Musicxml
         * @description #33: `ScorePreview`(OSMD)向けのプレビュー用MusicXML(FR-11)。
         *
         *     `POST /export`(#27)と同じ`render_musicxml`をそのまま再利用する
         *     (新規のレンダリングロジックは無い)。`POST /export`と異なり
         *     `storage.musicxml_export_path`には保存しない(こちらは編集のたびに
         *     都度再生成される一時プレビューであり、ユーザーが明示的にエクスポート
         *     した恒久成果物とは別物のため)。
         *
         *     小節範囲の絞り込み(設計書§11.5の`?bars=1-16`)はここでは実装しない:
         *     OSMD自身が`drawFromMeasureNumber`/`drawUpToMeasureNumber`オプションで
         *     描画範囲をクライアント側で絞り込めるため、常に全体のMusicXMLを返し
         *     フロントエンド側で絞る設計とする(#33-M3設計判断)。
         *
         *     `async def`ではなく通常の`def`にする(同ファイルの他エンドポイントと
         *     同じ理由): `render_musicxml`はpartitura呼び出しを含む同期CPUバウンド
         *     処理であり、`async def`のままだとイベントループを直接ブロックする。
         */
        get: operations["get_score_preview_musicxml_api_projects__project_id__score_preview_musicxml_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Score
         * @description 量子化(#25)+L0(#26)実行済みが前提。未実行なら404、不正なScore IRなら422を返す。
         *
         *     `async def` ではなく通常の `def` にする(`api/media.py`の`get_peaks`と同じ
         *     理由、#27-M2レビュー指摘): `render_musicxml`/`render_midi`はCPUバウンドの
         *     同期処理(partitura呼び出し)であり、`async def`のままだとイベントループを
         *     直接ブロックし、SSEでのジョブ進捗配信など他の同時リクエストを止めてしまう。
         */
        post: operations["export_score_api_projects__project_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BeatEntry */
        BeatEntry: {
            /** Time Sec */
            time_sec: number;
            /** Beat In Bar */
            beat_in_bar: number;
            /** Bar */
            bar: number;
        };
        /** Beatmap */
        Beatmap: {
            /** Beats */
            beats: components["schemas"]["BeatEntry"][];
            /** Downbeats Sec */
            downbeats_sec: number[];
            /** Time Signatures */
            time_signatures: components["schemas"]["TimeSignatureEntry"][];
            /** Tempo Map */
            tempo_map: components["schemas"]["TempoMapEntry"][];
            /** Confidence */
            confidence: number;
            /**
             * Source
             * @default auto
             */
            source: string;
        };
        /**
         * BeatmapEditRequest
         * @description #20 BeatGridEditor: 送られたフィールドのみ順に適用する(オフセット→BPM→回転→拍子)。
         */
        BeatmapEditRequest: {
            /** Offset Sec */
            offset_sec?: number | null;
            /** Bpm Override */
            bpm_override?: number | null;
            /**
             * Rotate Downbeat
             * @default false
             */
            rotate_downbeat: boolean;
            time_signature_override?: components["schemas"]["TimeSignatureEntry"] | null;
        };
        /** Body_create_project_api_projects_post */
        Body_create_project_api_projects_post: {
            /** File */
            file: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /**
         * ExportRequest
         * @description 設計書§11.6の`parts`/`options`による部分エクスポートはM3スコープ。
         *
         *     M2の完了条件(実曲からMusicXMLが出力されスキーマ的に妥当であること)には
         *     不要であり、`pipeline/export`側も現時点ではパート選択に対応していないため
         *     受け付けない。`extra="forbid"`(#27-M2レビュー指摘)により`parts`/`options`
         *     等の未知フィールドを黙って無視せず422で拒否する(Pydantic v2の既定
         *     `extra="ignore"`のままだと、送っても効果が無いのに送れてしまい、部分
         *     エクスポートが指定できたと誤認させる)。
         */
        ExportRequest: {
            /**
             * Format
             * @enum {string}
             */
            format: "musicxml" | "midi";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Job */
        Job: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Stage */
            stage: string;
            /** Status */
            status: string;
            /** Progress */
            progress: number;
            /** Message */
            message?: string | null;
            /** Exit Code */
            exit_code?: number | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * NoteAddOp
         * @description 新規ノートを追加する(FR-09)。
         *
         *     `onset_tick`/`duration_tick`を指定する(ピアノロールはtick空間で操作する
         *     ため)。`onset_sec`/`duration_sec`は`services/score_ops.py`が現在のbeatmap
         *     から逆算する。
         */
        NoteAddOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "note.add";
            /** Part Id */
            part_id: string;
            /** Onset Tick */
            onset_tick: number;
            /** Duration Tick */
            duration_tick: number;
            /** Midi */
            midi: number;
            /**
             * Velocity
             * @default 90
             */
            velocity: number;
            /**
             * Voice
             * @default 1
             */
            voice: number;
            /**
             * Staff
             * @default 1
             */
            staff: number;
        };
        /**
         * NoteDeleteOp
         * @description 論理削除(`status="deleted"`)。物理削除しない(§10.1)。
         */
        NoteDeleteOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "note.delete";
            /** Note Ids */
            note_ids: number[];
        };
        /**
         * NoteMergeOp
         * @description 複数ノート(同一pitch/voice/staff)を1つに結合する。
         *
         *     最も早い`onset_tick`から最も遅い終了tickまでを覆う1ノートに統合し、
         *     残りは論理削除する。
         */
        NoteMergeOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "note.merge";
            /** Note Ids */
            note_ids: number[];
        };
        /**
         * NoteRestoreOp
         * @description `note.delete`の逆操作(#35)。`status`を`"active"`へ戻す。
         *
         *     Undo(#32)は「直前の操作を取り消す」のに対し、本opは「この特定のノートを
         *     復元する」という別の意味を持つ(ピアノロール上で削除済みノートを
         *     クリックして復活させるUI操作に対応する、設計書§12.4「クリックで復活」)。
         */
        NoteRestoreOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "note.restore";
            /** Note Ids */
            note_ids: number[];
        };
        /**
         * NoteSplitOp
         * @description 1つのノートを`at_tick`で2つに分割する。
         */
        NoteSplitOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "note.split";
            /** Note Id */
            note_id: number;
            /** At Tick */
            at_tick: number;
        };
        /**
         * NoteUpdateOp
         * @description 既存ノートのプロパティ変更(複数ノートへの一括適用可)。
         *
         *     移動は`onset_tick`、リサイズは`duration_tick`の変更として表現する
         *     (設計書§10.4のop例が`note.update`を汎用的に使っているのと同じ設計)。
         *     未指定(`None`)のフィールドは変更しない。
         */
        NoteUpdateOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "note.update";
            /** Note Ids */
            note_ids: number[];
            /** Onset Tick */
            onset_tick?: number | null;
            /** Duration Tick */
            duration_tick?: number | null;
            /** Midi */
            midi?: number | null;
            /** Velocity */
            velocity?: number | null;
            /** Voice */
            voice?: number | null;
            /** Staff */
            staff?: number | null;
        };
        /**
         * PartTransposeOctaveOp
         * @description パート内の全activeノートを±1オクターブ移調する(R-6軽減策)。
         */
        PartTransposeOctaveOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "part.transpose_octave";
            /** Part Id */
            part_id: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "up" | "down";
        };
        /** PeaksResponse */
        PeaksResponse: {
            /** Duration Sec */
            duration_sec: number;
            /** Sample Rate */
            sample_rate: number;
            /** Peaks */
            peaks: number[][];
        };
        /** Project */
        Project: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Original Filename */
            original_filename: string;
            /** Audio Format */
            audio_format: string;
            /** Created At */
            created_at: string;
            /** Stages */
            stages: {
                [key: string]: components["schemas"]["StageStatus"];
            };
        };
        /** ProjectList */
        ProjectList: {
            /** Projects */
            projects: components["schemas"]["Project"][];
        };
        /** RunStageRequest */
        RunStageRequest: {
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: unknown;
            };
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /** RunStageResponse */
        RunStageResponse: {
            /** Job Id */
            job_id: string;
        };
        /**
         * ScoreOpsRequest
         * @description #31: `POST /score/ops`。配列で一括適用する(`domain/score_ops.py`参照)。
         */
        ScoreOpsRequest: {
            /** Ops */
            ops: (components["schemas"]["NoteAddOp"] | components["schemas"]["NoteUpdateOp"] | components["schemas"]["NoteDeleteOp"] | components["schemas"]["NoteRestoreOp"] | components["schemas"]["NoteSplitOp"] | components["schemas"]["NoteMergeOp"] | components["schemas"]["PartTransposeOctaveOp"])[];
        };
        /** StageStatus */
        StageStatus: {
            /** Status */
            status: string;
            /** Progress */
            progress: number;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
        };
        /**
         * StemListResponse
         * @description #21 TrackList: 分離済みステム名の一覧(拡張子抜き、順不同)。
         */
        StemListResponse: {
            /** Names */
            names: string[];
        };
        /** TempoMapEntry */
        TempoMapEntry: {
            /** Bar */
            bar: number;
            /** Beat */
            beat: number;
            /** Bpm */
            bpm: number;
        };
        /** TimeSignatureEntry */
        TimeSignatureEntry: {
            /** Bar */
            bar: number;
            /** Numerator */
            numerator: number;
            /** Denominator */
            denominator: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_project_api_projects_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_stage_api_projects__project_id__stages__stage__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                stage: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunStageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_events_api_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_original_audio_api_projects__project_id__audio_original_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/*": string;
                };
            };
            /** @description Partial Content */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/*": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stem_audio_api_projects__project_id__audio_stems__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/wav": string;
                };
            };
            /** @description Partial Content */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/wav": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stems_api_projects__project_id__stems_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StemListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_peaks_api_projects__project_id__analysis_peaks__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeaksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_beatmap_api_projects__project_id__analysis_beatmap_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Beatmap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_beatmap_api_projects__project_id__analysis_beatmap_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BeatmapEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Beatmap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_score_api_projects__project_id__score_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_score_ops_api_projects__project_id__score_ops_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoreOpsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description score not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description score modified concurrently */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    undo_score_ops_api_projects__project_id__score_undo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description score not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description score modified concurrently */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redo_score_ops_api_projects__project_id__score_redo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description score not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description score modified concurrently */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_score_preview_musicxml_api_projects__project_id__score_preview_musicxml_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.recordare.musicxml+xml": string;
                };
            };
            /** @description score not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description score is not quantized/spelled yet */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    export_score_api_projects__project_id__export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.recordare.musicxml+xml": string;
                    "audio/midi": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
